apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunspot-backend
  namespace: poc
  labels:
    name: sunspot-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sunspot-backend
  template:
    metadata:
      labels:
        app: sunspot-backend
    spec:
      containers:
      - name: sunspot-backend
        image: ashishkumar256/trace-api:1
        imagePullPolicy: Always     
        env:     
        - name: OTEL_SERVICE_NAME
          value: sunspot-backend
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: http/protobuf
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-agent-opentelemetry-collector.tracing.svc:4318
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: application=sunspot-backend
        - name: OTEL_PYTHON_LOG_CORRELATION
          value: "true"
        - name: OTEL_METRICS_EXPORTER
          value: none
        - name: OTEL_PYTHON_DISABLED_INSTRUMENTATIONS
          value: aws-lambda                                                                      
        - name: DJANGO_SETTINGS_MODULE
          value: backend.settings
        - name: REDIS_SERVER
          value: "127.0.0.1:6379"
        - name: OTEL_PYTHON_DJANGO_EXCLUDED_URLS
          value: "/status,^/admin/.*"
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /status
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /status
            port: 8000
          periodSeconds: 10          
      - name: redis
        image: redis
        imagePullPolicy: Always
        ports:
        - name: redis
          containerPort: 6379
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - redis-cli
            - PING
          periodSeconds: 60
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - redis-cli
            - PING
          periodSeconds: 60
          timeoutSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: sunspot-backend
  namespace: poc
spec:
  selector:
    app: sunspot-backend
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379