version: '3.9'
services:
  flask:
    network_mode: "host"
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env      
    volumes:
      - ./frontend:/app
    container_name: frontend
    command: opentelemetry-instrument python app.py
