apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunspot-frontend
  namespace: poc
  labels:
    name: sunspot-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sunspot-frontend
  template:
    metadata:
      labels:
        app: sunspot-frontend
    spec:
      containers:
      - name: sunspot-frontend
        image: ashishkumar256/trace-ui:1
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /status
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10       
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          periodSeconds: 10             
        env:     
        - name: OTEL_SERVICE_NAME
          value: sunspot-frontend
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: http/protobuf
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-agent-opentelemetry-collector.tracing.svc:4318
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: application=sunspot-frontend
        - name: OTEL_PYTHON_LOG_CORRELATION
          value: "true"
        - name: OTEL_METRICS_EXPORTER
          value: none
        - name: OTEL_PYTHON_DISABLED_INSTRUMENTATIONS
          value: aws-lambda
        - name: SUNSPOT_BACKEND_ENDPOINT
          value: "http://sunspot-backend.poc.svc.cluster.local:8000"                                                                            

---
apiVersion: v1
kind: Service
metadata:
  name: sunspot-frontend
  namespace: poc
spec:
    selector:
      app: sunspot-frontend
    ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: redis-port
      protocol: TCP
      port: 6379
      targetPort: 6379          